### ISSUE TITLE
Please wait message, then almost empty mp3 file gets dowloaded

### ISSUE THREAD

**Issue by mikeymckay** [miracsengonul/chatgpt-sound-downloader#3]
When I view the downloaded file:

{"detail":[{"type":"enum","loc":["query","voice"],"msg":"Input should be 'breeze', 'cove', 'ember', 'fathom', 'harp', 'juniper', '__internal_only_santa', 'sky', 'alloy', 'echo' or 'shimmer'","input":"__internal_only_shimmer","ctx":{"expected":"'breeze', 'cove', 'ember', 'fathom', 'harp', 'juniper', '__internal_only_santa', 'sky', 'alloy', 'echo' or 'shimmer'"}}]}

Looks like "shimmer" isn't supported, so needs to be removed from the voice options.

**Comment by miracsengonul** [comment]
Thanks @mikeymckay , yes it was a problem I realised. Thank you for the improvement.
