### ISSUE TITLE
Failed to retrieve necessary information for download

### ISSUE THREAD

**Issue by rafaelkapela** [miracsengonul/chatgpt-sound-downloader#7]
Error: Failed to retrieve necessary information for download

messageId: 149167ca-2d70-4be2-b3ca-a15109a2aad5
content.js:79 conversationId: 66f7131d-58b4-8006-ab14-27571b041540
content.js:80 accessToken: null

**Comment by miracsengonul** [comment]
**Important Note:** Using a VPN or other browser extensions may cause unexpected issues. To accurately diagnose the problem, we recommend testing our extension in a clean browser profile (with other extensions disabled and VPN turned off).

**Comment by kaevinio** [comment]
I encounter the same error. No VPN is used and all other extensions are disabled. Also restarted chrome, but the same error
<img width="614" alt="Bildschirmfoto 2024-09-29 um 12 40 47" src="https://github.com/user-attachments/assets/988f2b21-cee5-4580-b916-8cb863e0c0e0">

**Comment by miracsengonul** [comment]
I've just released a new update to fix the token authentication issues.
